version: '3.8'

# SLURM集群Docker Compose配置
services:
  # SLURM控制器节点
  slurmctld:
    image: ubuntu:22.04
    container_name: slurmctld
    hostname: slurmctld
    networks:
      - slurm_network
    ports:
      - "6817:6817"  # SLURM控制器端口
      - "6818:6818"  # SLURM守护进程端口
      - "6819:6819"  # SLURM数据库端口
    volumes:
      - ./shared:/shared
      - ./slurm/slurm.conf:/etc/slurm/slurm.conf:ro
      - slurmctld_state:/var/spool/slurmctld
    environment:
      - SLURM_CONF=/etc/slurm/slurm.conf
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y slurm-wlm munge && create-munge-key && chown munge:munge /etc/munge/munge.key && chmod 600 /etc/munge/munge.key && service munge start && slurmctld -D"]
    restart: unless-stopped

  # 计算节点1
  compute1:
    image: ubuntu:22.04
    container_name: compute1
    hostname: compute1
    networks:
      - slurm_network
    volumes:
      - ./shared:/shared
      - ./slurm/slurm.conf:/etc/slurm/slurm.conf:ro
      - compute1_state:/var/spool/slurmd
    environment:
      - SLURM_CONF=/etc/slurm/slurm.conf
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y slurm-wlm munge && service munge start && slurmd -D"]
    depends_on:
      - slurmctld
    restart: unless-stopped

  # 计算节点2
  compute2:
    image: ubuntu:22.04
    container_name: compute2
    hostname: compute2
    networks:
      - slurm_network
    volumes:
      - ./shared:/shared
      - ./slurm/slurm.conf:/etc/slurm/slurm.conf:ro
      - compute2_state:/var/spool/slurmd
    environment:
      - SLURM_CONF=/etc/slurm/slurm.conf
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y slurm-wlm munge && service munge start && slurmd -D"]
    depends_on:
      - slurmctld
    restart: unless-stopped

  # 登录节点
  login:
    image: ubuntu:22.04
    container_name: login
    hostname: login
    networks:
      - slurm_network
    ports:
      - "2222:22"  # SSH端口
    volumes:
      - ./shared:/shared
      - ./slurm/slurm.conf:/etc/slurm/slurm.conf:ro
    environment:
      - SLURM_CONF=/etc/slurm/slurm.conf
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y slurm-client munge openssh-server && service munge start && service ssh start && tail -f /dev/null"]
    depends_on:
      - slurmctld
    restart: unless-stopped

networks:
  slurm_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  slurmctld_state:
  compute1_state:
  compute2_state: